export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'
export const CART_CLEAR_ITEMS = 'CART_CLEAR_ITEMS'

export const SHIPPTING_ADDRESS_REQUEST = 'SHIPPTING_ADDRESS_REQUEST'
export const SHIPPTING_ADDRESS_SUCCESS = 'SHIPPTING_ADDRESS_SUCCESS'
export const SHIPPTING_ADDRESS_FAIL = 'SHIPPTING_ADDRESS_FAIL'



export const ORDER_ITEM_REQUEST = 'ORDER_ITEM_REQUEST'
export const ORDER_ITEM_SUCCESS = 'ORDER_ITEM_SUCCESS'
export const ORDER_ITEM_FAIL = 'ORDER_ITEM_FAIL'