export const ALL_NESTED_CATEGORY_REQUEST = 'ALL_NESTED_CATEGORY_REQUEST'
export const ALL_NESTED_CATEGORY_SUCCESS = 'ALL_NESTED_CATEGORY_SUCCESS'
export const ALL_NESTED_CATEGORY_FAIL = 'ALL_NESTED_CATEGORY_FAIL'


