export const CUSOTMER_REGISTER_REQUEST = "CUSOTMER_REGISTER_REQUEST"
export const CUSOTMER_REGISTER_SUCCESS = 'CUSTOMER_REGISTER_SUCCESS'
export const CUSOTMER_REGISTER_FAIL = 'CUSTOMER_REGISTER_FAIL'


export const CUSOTMER_LOGIN_REQUEST = "CUSOTMER_LOGIN_REQUEST"
export const CUSOTMER_LOGIN_SUCCESS = 'CUSOTMER_LOGIN_SUCCESS'
export const CUSOTMER_LOGIN_FAIL = 'CUSOTMER_LOGIN_FAIL'


export const CUSTOMER_DETAILS_INFORMATION_REQUEST = 'CUSTOMER_DETAILS_INFORMATION_REQUEST'
export const CUSTOMER_DETAILS_INFORMATION_SUCCESS = 'CUSTOMER_DETAILS_INFORMATION_SUCCESS'
export const CUSTOMER_DETAILS_INFORMATION_FAIL = 'CUSTOMER_DETAILS_INFORMATION_FAIL'
