# Generated by Django 4.0.1 on 2022-06-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_order_customer_name_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
