# Generated by Django 4.0.1 on 2022-07-03 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_order_order_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Order_details',
        ),
    ]
