# Generated by Django 4.0.1 on 2022-07-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_shippingaddress_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
