# Generated by Django 4.0.1 on 2022-07-06 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_order_grand_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='payment_method',
        ),
    ]
