# Generated by Django 4.0.1 on 2022-07-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_order_order_date_order_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_qty',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
