# Generated by Django 4.0.1 on 2022-07-16 05:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0018_alter_sellerprofile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SellerProfile',
            new_name='Seller_profile',
        ),
    ]
