# Generated by Django 4.0.1 on 2022-07-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_seller_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
