# Generated by Django 4.0.1 on 2022-07-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_product_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
