# Generated by Django 4.0.1 on 2022-07-20 06:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_order_details_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='listed_seller',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=512, null=True), blank=True, null=True, size=None),
        ),
    ]
