# Generated by Django 4.0.1 on 2022-07-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_order_associated_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='listed_seller',
        ),
    ]
