# Generated by Django 4.0.1 on 2022-07-24 02:55

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_order_listed_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.IntegerField(blank=True, default=app.models.order_no_generate, null=True),
        ),
    ]
