# Generated by Django 4.0.1 on 2022-08-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_order_details_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_details',
            old_name='seller_id',
            new_name='customer_or_seller',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='customer',
        ),
    ]
