# Generated by Django 4.0.1 on 2022-08-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_rename_seller_id_order_details_customer_or_seller_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_details',
            old_name='customer_or_seller',
            new_name='seller_id',
        ),
    ]
