# Generated by Django 4.0.1 on 2022-12-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_rename_customer_or_seller_order_details_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_profile',
            name='active',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
