# Generated by Django 4.0.1 on 2022-12-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_seller_profile_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='adminaccess',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
