# Generated by Django 4.0.1 on 2022-12-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_userprofile_adminaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='adminaccess',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
