export const CATEGORY_REQUEST = "CATEGORY_REQUEST"
export const CATEGORY_SUCCESS = "CATEGORY__SUCCESS"
export const CATEGORY_FAIL = "CATEGORY__FAIL"

export const SUB_CATEGORY_REQUEST = "SUB_CATEGORY_REQUEST"
export const SUB_CATEGORY_SUCCESS = "SUB_CATEGORY__SUCCESS"
export const SUB_CATEGORY_FAIL = "SUB_CATEGORY__FAIL"


export const SUB_SUB_CATEGORY_REQUEST = "SUB_SUB_CATEGORY_REQUEST"
export const SUB_SUB_CATEGORY_SUCCESS = "SUB_SUB_CATEGORY__SUCCESS"
export const SUB_SUB_CATEGORY_FAIL = "SUB_SUB_CATEGORY__FAIL"




export const BRAND_REQUEST = "BRAND_REQUEST"
export const BRAND_SUCCESS = "BRAND_SUCCESS"
export const BRAND_FAIL = "BRAND_FAIL"



