export const ALL_ORDER_REQUEST = "ALL_ORDER_REQUEST"
export const ALL_ORDER_SUCCESS = "ALL_ORDER_SUCCESS"
export const ALL_ORDER_FAIL = "ALL_ORDER_FAIL"



export const PENDING_ORDER_REQUEST = "PENDING_ORDER_REQUEST"
export const PENDING_ORDER_SUCCESS = "PENDING_ORDER_SUCCESS"
export const PENDING_ORDER_FAIL = "PENDING_ORDER_FAIL"



export const RTS_ORDER_REQUEST = "RTS_ORDER_REQUEST"
export const RTS_ORDER_SUCCESS = "RTS_ORDER_SUCCESS"
export const RTS_ORDER_FAIL = "RTS_ORDER_FAIL"



export const CANCELLED_REQUEST = "CANCELLED_REQUEST"
export const CANCELLED_SUCCESS = "CANCELLED_SUCCESS"
export const CANCELLED_FAIL = "CANCELLED_FAIL"


export const ALL_CANCELLED_REQUEST = "ALL_CANCELLED_REQUEST"
export const ALL_CANCELLED_SUCCESS = "ALL_CANCELLED_SUCCESS"
export const ALL_CANCELLED_FAIL = "ALL_CANCELLED_FAIL"


export const ALL_ORDER_DETAILS_REQUEST = 'ALL_ORDER_DETAILS_REQUEST'
export const ALL_ORDER_DETAILS_SUCCESS = 'ALL_ORDER_DETAILS_SUCCESS'
export const ALL_ORDER_DETAILS_FAIL = 'ALL_ORDER_DETAILS_FAIL'



export const INVOICE_REQUEST = 'INVOICE_REQUEST'
export const INVOICE_SUCCESS = 'INVOICE_SUCCESS'
export const INVOICE_FAIL = 'INVOICE_FAIL'






