export const PRODUCT_ADD_REQUEST = "PRODUCT_ADD_REQUEST"
export const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD_SUCCESS"
export const PRODUCT_ADD_FAIL = "PRODUCT_ADD_FAIL"


export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS"
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"


export const COLOR_REQUEST = "COLOR_REQUEST"
export const COLOR_SUCCESS = "COLOR_SUCCESS"
export const COLOR_FAIL = "COLOR_FAIL"



export const PUBLISH_REQUEST = "PUBLISH_REQUEST"
export const PUBLISH_SUCCESS = "PUBLISH_SUCCESS"
export const PUBLISH_FAIL = "PUBLISH_FAIL"


export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST"
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS"
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL"



export const PRODUCT_DELETE_MANY_REQUEST = "PRODUCT_DELETE_MANY_REQUEST"
export const PRODUCT_DELETE_MANY_SUCCESS = "PRODUCT_DELETE_MANY_SUCCESS"
export const PRODUCT_DELETE_MANY_FAIL = "PRODUCT_DELETE_MANY_FAIL"


export const GENERATE_SKU_REQUEST = "GENERATE_SKU_REQUEST"
export const GENERATE_SKU_SUCCESS = "GENERATE_SKU_SUCCESS"
export const GENERATE_SKU_FAIL = "GENERATE_SKU_FAIL"



export const PRODUCT_STOCK_REQUEST = "PRODUCT_STOCK_REQUEST"
export const PRODUCT_STOCK_SUCCESS = "PRODUCT_STOCK_SUCCESS"
export const PRODUCT_STOCK_FAIL = "PRODUCT_STOCK_FAIL"